#!/bin/bash

echo "___Pact Broker SafS___"
echo "______________________"
echo "__Available Commands__"
echo "______________________"
echo "pactsafs help"
echo "pactsafs list"
echo "pactsafs deploy <tenant_name> <tenant_port>"
echo "pactsafs stop <tenant_name>"
echo "pactsafs remove <tenant_name>"
echo "pactsafs backup <tenant_name>"
echo "pactsafs restore <tenant_name>"
echo "______________________"
